# Generated by Django 5.0 on 2024-01-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0002_alter_perfil_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="data_nacimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
