# Generated by Django 5.0 on 2024-01-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil", "0003_alter_perfil_cpf_alter_perfil_data_nacimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="complemento",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
