# Generated by Django 5.0 on 2024-01-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_varicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varicao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
