# Generated by Django 5.0 on 2024-01-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0003_alter_varicao_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
