# Generated by Django 5.0 on 2024-01-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0004_alter_produto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing",
            field=models.FloatField(verbose_name="Perço"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing_promocional",
            field=models.FloatField(default=0, verbose_name="Preço Promocional"),
        ),
    ]
