# Generated by Django 5.0 on 2024-01-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varicao',
            new_name='Variacao',
        ),
    ]
