# Generated by Django 5.0 on 2024-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedido", "0002_pedido_qtd_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="imagem",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="itempedido",
            name="preco_promocional",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
